# -*- coding: utf-8 -*-
"""Chatbot.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GSNq3HjTz4wXU6tHxUGfqVThlUtkLLLl
"""

!pip install transformers
!pip install torch==1.4.0

from transformers import pipeline, Conversation
conversational_pipeline = pipeline("conversational")

conv1_start = "Let's watch a movie tonight - any recommendations?"
conv2_start = "What's your favorite book?"

conv1 = Conversation(conv1_start)
conv2 = Conversation(conv2_start)

conversational_pipeline([conv1, conv2])

conv1_next = "What is it about?"
conv2_next = "Cool, what is the genre of the book?"

conv1.add_user_input(conv1_next)
conv2.add_user_input(conv2_next)

conversational_pipeline([conv1, conv2])

conv1_cont = "Are you a girl or a boy?"
conv2_cont = "Can I call you Mary?"

conv1.add_user_input(conv1_cont)
conv2.add_user_input(conv2_cont)

conversational_pipeline([conv1, conv2])